=encoding utf8

=head1 pl-HashCracken

Perl script to crack hashes in online database


=head2 Install dependence

	sudo cpanm  --installdeps .

=head2 Edit config.json

	{
		"threads": 10, // number of asynchronous requests

		// Input and Output files
		"outputGood": "outputGood.txt",  // Cracked hashes list like this "81dc9bdb52d04dc20036dbd8313ed055:1234	(md5)"
		"outputBad": "outputBad.txt" // Not cracked hashes
		"input": "input.txt", // Hash list
	}


=head2 Edit services.json

	{
		"hashType": "md5", // Hesh type
		"inputFilter": "^[a-z0-9]{32}$", // Expression coincides with the hash

		"service": "md5online.net", // Servise name
		"request": {
			"method": "POST", // Request method GET or POST
			"uri": "http://md5online.net/", // Request url

			// Post params
			"data": {
				"pass": "{HASH}",
				"option": "hash2text",
				"send": "Submit"
			}

			// If use get request, section date must be equal to {}
			// In params and url text {HASH} is replaced by your hash 
		},
		
		// Regexp to parsing respons
		"responsRegexp": "<br>pass : <b>(.+?)</b></p></table>"
	},

=head2 Start script

	git clone git@github.com:maximusfox/pl-HashCracken.git
	cd pl-HashCracken
	sudo cpanm  --installdeps .
	chmod +x start.pl
	./start.pl [OPTIONS]

=head2 Usage

	usage: start.pl [OPTIONS...]

	  Options:
	    --help,       -h    Show help message
	    --header,     -hd   Show or not header information [on|off] (default on)
	    --in,         -i    Input file (default input.txt)
	    --good,       -g    Good output file (default good.txt)
	    --bad,        -b    Bad output file (default bad.txt)
	    --config,     -C    JSON config file (default config.json)
	    --services,   -S    JSON services config file (default services.json)
	    --threads,    -t    Number of asynchronous requests (default 10)
	    --colored,    -c    Colored output
	    --proxy,      -p    Use proxy (like this http://localhost:8888/), not use it with --debugProxy
	    --debug,      -d    Set debug mod
	    --debugProxy, -dp   Set charles debug proxy (http://localhost:8888/), not use it with --proxy

=head2 Working output

	[fox@BuldoserX4 pl-HashCracken]$ ./start.pl 
	# HashCracken v0.1
	# Author: SHok
	# GitHub.com https://github.com/maximusfox/pl-HashCracken
	# Jabber: avchecking@cryptovpn.com

	[-] Service[md5online.net (md5) ]	8ed36a8485e30937b99c0d247e9c3832
	[+] Service[md5online.net (md5) ]	81dc9bdb52d04dc20036dbd8313ed055:1234
	[-] Service[md5pass.info (md5) ]	8ed36a8485e30937b99c0d247e9c3832
	[-] Service[md5online.net (md5) ]	25b1902406e1629d19f07bba8b2f0cf0
	[-] Service[md5pass.info (md5) ]	25b1902406e1629d19f07bba8b2f0cf0
	[+] Service[md5crack.com (md5) ]	8ed36a8485e30937b99c0d247e9c3832:3390
	[-] Service[md5crack.com (md5) ]	25b1902406e1629d19f07bba8b2f0cf0
	[+] Service[stringfunction.com (sha1) ]	5baa61e4c9b93f3f0682250b6cf8331b7ee68fd8:password
	[+] Service[stringfunction.com (md5) ]	25b1902406e1629d19f07bba8b2f0cf0:salo
